jobs/urls.py
from django.urls import path
from . import views as jobs_views


urlpatterns = [
    path('', jobs_views.index, name='index'),
    path('createEmpresa/', jobs_views.signup_empresa, name='empresa_signup'),
    path('createCandidato/', jobs_views.signup_candidato, name='candidato_signup'),
    path('home/', jobs_views.home, name='home'),
    path('homeEmpresa/', jobs_views.home_empresa, name='home_to_empresa'),
    path('homeCandidato/', jobs_views.home_candidato, name='home_to_candidato'),
    path('<int:pk>/inscrever', jobs_views.inscrever_vaga, name='inscrever_vaga'),
    path('vaga/', jobs_views.VagaListView.as_view(), name='vagas'),
    path('vaga/<int:pk>', jobs_views.VagaDetail.as_view(), name='vaga_details'),
    path('vaga/create/', jobs_views.CreateVaga.as_view(), name='create_vaga'),
    path('vaga/<int:pk>/update/', jobs_views.UpdateVaga.as_view(), name='update_vaga'),
    path('vaga/<int:pk>/delete/', jobs_views.DeleteVaga.as_view(), name='delete_vaga'),
    path('errorDuplicate/', jobs_views.error_duplicate, name='duplicate'),
    path('inscricoesFeitas/', jobs_views.InscricoesVagasListView.as_view(), name='inscricoes_feitas'),
    path('vagaDetail/<int:pk>', jobs_views.VagaDetailEmpresa.as_view(), name='vaga_empresa_details'),

]

provaDeConceito/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('jobs.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jobs/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.urls import reverse

from provaDeConceito import settings

# Create your models here.


class MyUserManager(BaseUserManager):
    def create_user(
            self,
            email,
            first_name,
            last_name,
            password=None
    ):
        """
        Cria e salva um usuário com o email, primeiro nome, último nome, data de nascimento e senha.
        """
        if not email:
            raise ValueError("Nome de usuário deve ser um email")

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(
            self,
            email,
            first_name,
            last_name,
            password
    ):
        """
        Cria e salva superuser, com email, primeiro nome, último nome, data de nascimento e senha.
        """
        user = self.create_user(
            email,
            first_name=first_name,
            last_name=last_name,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name="Endereço de e-mail", max_length=255, unique=True)
    first_name = models.CharField(verbose_name="Primeiro nome", max_length=255)
    last_name = models.CharField(verbose_name="Sobrenome", max_length=255)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    def __str__(self):
        return self.first_name + " " + self.last_name

    def get_full_name(self):
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        return self.first_name

    def has_perm(self, perm, obj=None):
        """Método para tratar se o usuário possui permissões especiais"""
        return True

    def has_module_perms(self, app_label):
        """Método para tratar se o usuário possui permissão para ver a label app"""
        return True

    @property
    def is_staff(self):
        """Se o usuário for um membro do staff?"""
        return self.is_admin


class Empresa(models.Model):
    empresa = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    cnpj = models.BigIntegerField(verbose_name="CNPJ da empresa")
    atividade = models.CharField(verbose_name="Atividade principal da empresa", max_length=255)
    nome_empresa = models.CharField(verbose_name="Nome da Empresa", max_length=255)

    def __str__(self):
        return self.nome_empresa


class Candidato(models.Model):
    ESCOLARIDADE = (
        ("1", "Sem escolaridade"),
        ("2", "Primário"),
        ("3", "Ensino Fundamental"),
        ("4", "Ensino Médio"),
        ("5", "Ensino Superior"),
        ("6", "Pos Graduação ou MBA"),
        ("7", "Mestrado"),
        ("8", "Doutorado"),
        ("9", "PHD - Pós Doutorado")
    )
    candidato = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pretensao_salarial = models.FloatField(verbose_name="Pretensão salarial")
    experiencia = models.TextField(verbose_name="Experiência do usuário", max_length=500)
    escolaridade = models.CharField(verbose_name="Nível de escolaridade", max_length=1, choices=ESCOLARIDADE,
                                    blank=True, null=True)


class Vaga(models.Model):
    FAIXA_SALARIAL = (
        ("1", "Até R$ 1000,00"),
        ("2", "De R$ 1000,00 a R$ 2000,00"),
        ("3", "De R$ 2000,00 a R$ 3000,00"),
        ("4", "Acima de R$ 4000,00"),
    )
    ESCOLARIDADE = (
        ("1", "Ensino Fundamental"),
        ("2", "Ensino Médio"),
        ("3", "Tecnológo"),
        ("4", "Ensino Superior"),
        ("5", "Pos Graduação, MBA, Mestrado"),
        ("6", "Doutorado"),
    )
    nome_vaga = models.CharField(verbose_name="Descrição da vaga", max_length=255)
    faixa_salaria = models.CharField(verbose_name="Faixa Salarial", max_length=1, choices=FAIXA_SALARIAL)
    requisitos = models.CharField(verbose_name="Requisitos", max_length=500)
    escolaridade_min = models.CharField(verbose_name="Escolaridade Minima", max_length=1, choices=ESCOLARIDADE)
    empresa_responsavel = models.ForeignKey(Empresa, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('vaga_details', args=[str(self.id)])

    def __str__(self):
        return self.nome_vaga


class InscricaoVaga(models.Model):
    candidato = models.ForeignKey(Candidato, on_delete=models.CASCADE)
    vaga = models.ForeignKey(Vaga, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("candidato", "vaga")

    def __str__(self):
        return self.vaga.nome_vaga

jobs/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import Empresa, Candidato, InscricaoVaga

User = get_user_model()


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=255, required=True)
    last_name = forms.CharField(max_length=255, required=True)

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'password1', 'password2')


class SignUpFormEmpresa(forms.ModelForm):
    class Meta:
        model = Empresa
        exclude = ('empresa',)


class SignUpFormCandidato(forms.ModelForm):
    class Meta:
        model = Candidato
        exclude = ('candidato',)


class IncreverVagaForm(forms.Form):
    mensagem = forms.CharField(help_text="Adicione uma mensagem para o recrutador")

    def clean_mensagem(self):
        data = self.cleaned_data['mensagem']
        return data

jobs/views.py
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError

from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView

from .forms import SignUpForm, SignUpFormEmpresa, SignUpFormCandidato
from .models import Vaga, InscricaoVaga, Candidato, Empresa


# Create your views here.
def index(request):
    return render(request, 'base.html')


def success(request):
    return render(request, 'success.html')


def home_candidato(request):
    return render(request, 'homeCandidato.html')


def home_empresa(request):
    return render(request, 'homeEmpresa.html')


@login_required(login_url='/accounts/login')
def home(request):
    try:
        if Candidato.objects.get(candidato=request.user):
            return redirect('home_to_candidato')
    except Candidato.DoesNotExist:
        pass
    try:
        if Empresa.objects.get(empresa=request.user):
            return redirect('home_to_empresa')
    except Empresa.DoesNotExist:
        return redirect('login')


def signup_empresa(request):
    if request.method == 'POST':
        form1 = SignUpForm(request.POST)
        form2 = SignUpFormEmpresa(request.POST)
        if all([form1.is_valid(), form2.is_valid()]):
            model1 = form1.save()
            model2 = form2.save(commit=False)
            model2.empresa = model1
            model2.save()
            return redirect('home')
    else:
        form1 = SignUpForm()
        form2 = SignUpFormEmpresa()
    return render(request, 'createEmpresa.html', {'form1': form1, 'form2': form2})


def signup_candidato(request):
    if request.method == 'POST':
        form1 = SignUpForm(request.POST)
        form2 = SignUpFormCandidato(request.POST)
        if all([form1.is_valid(), form2.is_valid()]):
            model1 = form1.save()
            model2 = form2.save(commit=False)
            model2.candidato = model1
            model2.save()
            return redirect('home')
    else:
        form1 = SignUpForm()
        form2 = SignUpFormCandidato()
    return render(request, 'createCandidato.html', {'form1': form1, 'form2': form2})


class VagaListView(generic.ListView):
    model = Vaga


class VagaDetail(generic.DetailView):
    model = Vaga


class VagaDetailEmpresa(generic.DetailView):
    model = Vaga
    template_name = 'jobs/listVaga_empresa.html'


class CreateVaga(CreateView):
    model = Vaga
    fields = '__all__'
    success_url = reverse_lazy('vagas')


class UpdateVaga(UpdateView):
    model = Vaga
    fields = ['nome_vaga', 'faixa_salaria', 'requisitos', 'escolaridade_min']


class DeleteVaga(DeleteView):
    model = Vaga
    success_url = reverse_lazy('inscricoes_feitas')


def inscrever_vaga(request, pk):
    if request.method == 'POST':
        try:
            inscricao = InscricaoVaga()
            inscricao.vaga = Vaga.objects.get(id=pk)
            inscricao.candidato = Candidato.objects.get(candidato=request.user)
            inscricao.save()
        except IntegrityError as e:
            return redirect("duplicate")
    return redirect('vagas')


def error_duplicate(request):
    return render(request, 'duplicate_error.html')


class InscricoesVagasListView(generic.ListView):
    model = InscricaoVaga
    template_name = 'jobs/vagas_com_inscricoes.html'

    def get_queryset(self):
        return InscricaoVaga.objects.all()

templates/jobs/listVaga_empresa.html
{% extends 'base.html' %}
{% block content %}
    {% include "jobs/navbar.html" %}
    <div class="task-container column is-multiline">
        <div class="card column is-half is-offset-one-quarter">
            <header class="card-header">
                <p class="card-header-title">Vaga: {{ vaga }}</p>
            </header>
            <div class="card-content">
                <div class="content">
                    <p>{{ vaga.nome_vaga }}</p>
                    <p>{{ vaga.empresa_responsavel }}</p>
                    <p>{{ vaga.get_escolaridade_min_display }}</p>
                    <p>{{ vaga.get_faixa_salaria_display }}</p>
                    <p>{{ vaga.requisitos }}</p>
                </div>
            </div>
            <footer class="card-footer">
                <form method="post" action="{% url 'delete_vaga' vaga.id %}">
                    {% csrf_token %}
                    <input type="submit" value="Deletar vaga">
                </form>
            </footer>
        </div>
    </div>
{% endblock %}

templates/jobs/navbar.html
<nav class="navbar">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'home_to_empresa' %}">
                <strong>Empresa Home</strong>
            </a>
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a class="button is-info" href="{% url 'home_to_empresa' %}">
                        <strong>Home</strong>
                    </a>
                    <a class="button is-primary" href="{% url 'create_vaga' %}">
                        <strong>Criar Vaga</strong>
                    </a>
                    <a class="button is-link" href="{% url 'inscricoes_feitas' %}">
                        <strong>Ver inscrições feitas</strong>
                    </a>
                    <a class="button is-danger" href="{% url 'logout' %}">
                        <strong>Logout</strong>
                    </a>
                </div>
            </div>
        </div>
    </nav>

templates/jobs/navbar_candidato.html
<nav class="navbar">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'home_to_candidato' %}">
                <strong>Candidato Home</strong>
            </a>
        </div>
        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    <a class="button is-info" href="{% url 'home_to_candidato' %}">
                        <strong>Home</strong>
                    </a>
                    <a class="button is-link" href="{% url 'vagas' %}">
                        <strong>Ver vagas</strong>
                    </a>
                    <a class="button is-danger" href="{% url 'logout' %}">
                        <strong>Logout</strong>
                    </a>
                </div>
            </div>
        </div>
    </nav>

templates/jobs/vaga_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div>
        {% include "jobs/navbar.html" %}
    </div>
    <form method="post">
        <p>Você te certeza que vai deletar a vaga? {{ vaga }}</p>
    </form>
{% endblock %}

templates/jobs/vaga_detail.html
{% extends 'base.html' %}
{% block content %}
    {% include "jobs/navbar_candidato.html" %}
    <div class="task-container column is-multiline">
        <div class="card column is-half is-offset-one-quarter">
            <header class="card-header">
                <p class="card-header-title">Vaga: {{ vaga }}</p>
            </header>
            <div class="card-content">
                <div class="content">
                    <p>{{ vaga.nome_vaga }}</p>
                    <p>{{ vaga.empresa_responsavel }}</p>
                    <p>{{ vaga.get_escolaridade_min_display }}</p>
                    <p>{{ vaga.get_faixa_salaria_display }}</p>
                    <p>{{ vaga.requisitos }}</p>
                </div>
            </div>
            <footer class="card-footer">
                <form method="post" action="{% url 'inscrever_vaga' vaga.id %}">
                    {% csrf_token %}
                <input type="submit" value="Inscrever Vaga">
                </form>
            </footer>
        </div>
    </div>
{% endblock %}

templates/jobs/vaga_form.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
{% endblock %}

templates/jobs/vaga_list.html
{% extends 'base.html' %}
{% block content %}
    <div>
        {% include "jobs/navbar_candidato.html" %}
    </div>
    <div class="section">
        <div class="container">
            <h2 class="title">
                Lista de Vagas
            </h2>
            {% if vaga_list %}
                {% for vaga in vaga_list %}
                    <div class="columns">
                        <div class="column">
                            <a href="{{ vaga.get_absolute_url }}">
                                {{ vaga.nome_vaga }}
                            </a>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div>Não há vagas cadastradas.</div>
            {% endif %}
        </div>
    </div>
{% endblock %}

templates/jobs/vagas_com_inscricoes.html
{% extends 'base.html' %}
{% block content %}
    <div>
        {% include "jobs/navbar.html" %}
    </div>
    <div>
        {% if inscricaovaga_list %}
            <ul>
                {% for inscricao in inscricaovaga_list %}
                    <div class="task-container column is-multiline">
                        <div class="card column is-half is-offset-one-quarter">
                            <header class="card-header">
                            <p class="card-header-title">Vaga: {{ inscricao }}</p>
                        </header>
                        <div class="card-content">
                            <div class="content">
                                <p>Nome Candidato: {{ inscricao.candidato.candidato.first_name }} </p>
                                <p>Escolaridade: {{ inscricao.candidato.escolaridade }} </p>
                                <p>Pretensão Salarial: {{ inscricao.candidato.pretensao_salarial }} </p>
                                <p>Experiência do Candidato: {{ inscricao.candidato.experiencia }} </p>
                            </div>
                        </div>
                        <footer class="card-footer">
                            <a href="{% url 'vaga_empresa_details' inscricao.vaga.id %}">
                                Detalhes da Vaga
                            </a>
                        </footer>
                        </div>
                    </div>
                {% endfor %}
            </ul>
        {% else %}

        {% endif %}
    </div>
{% endblock %}